# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
dockitems_persist: []

dotfiles_repo: https://github.com/mizx/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .p10k.zsh
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - doppler
  - flyctl
  - gettext
  - gifsicle
  - git
  - gh
  - node
  - nvm
  - pnpm
  - readline
  - temporal
  - thefuck
  - wget
  - wireguard-tools
  - yarn
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - discord
  - docker
  - dropbox
  - figma
  - firefox
  - github
  # - google-chrome # already installed
  - gpg-suite
  - handbrake
  - iterm2
  - lastpass
  - postgres-unofficial
  - postman
  # - slack # already installed
  - spotify
  - visual-studio-code

osx_script: "~/.osx --no-restart"
