# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - Keynote
  - Numbers
  - Pages
  - App Store
  - System Settings
dockitems_persist:
  - name: Chrome
    path: "/Applications/Google Chrome.app"
  - name: "Cursor"
    path: "/Applications/Cursor.app"
  - name: Discord
    path: "/Applications/Discord.app"
  - name: Spotify
    path: "/Applications/Spotify.app"
  - name: Keeper
    path: "/Applications/Keeper Password Manager.app"

dotfiles_repo: https://github.com/mizx/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .p10k.zsh
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - docker
  - gettext
  - gifsicle
  - git
  - gh
  - homeassistant-cli
  - node
  - nvm
  - pnpm
  - powerlevel10k
  - readline
  - thefuck
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - cursor
  - discord
  - docker
  - firefox
  - font-meslo-lg-nerd-font
  - github
  - google-chrome
  - keeper-password-manager
  - home-assistant
  - iterm2
  - spotify
  - visual-studio-code

osx_script: "~/.osx --no-restart"
